### ISSUE TITLE
V2.0 not working with herokuapp.com anymore

### ISSUE THREAD

**Issue by dpishta** [Matze1985/GlucoTT#5]
It asks for azurewebsite link on startup

**Comment by Matze1985** [comment]
Hi, 

is the new update better?

Version 2.1

BR Mathias

**Comment by Matze1985** [comment]
Fixed with commit https://github.com/Matze1985/GlucoTT/commit/4eb1b7914250c2d4140f6c06dbe05b4435e211f6
